Sprint 5/cof 63
Damir-prg/coffee-owls pull request #21
Opened 2024-05-06 19:27 UTC by Damir-prg

### Добавлен Canvas игры и логика отрисовки ячеек

**Изменено:**
- Наименование режима игры вынесено в константы, для правильного отображения текста, чтобы не дублировать код
- `GameContentContainer` вынесен в `ScreenSwitcher`, чтобы не оборачивать им `Canvas`
- Кнопка "Повторить игру" теперь ведёт сразу на `Canvas`
- Правило по наименованию класса, так как правило `typeLike` затрагивало и их
- Время отсчета перед началом игры

**Добавлено:**
- Класс `Board` для инициализации и управления доски с ячейками
- - В классе `Board` реализовано:
- - - Независимость отрисовки ячеек от выбранного количества элементов в строке/столбце
- - - Создание ячейки на доске
- - - Отрисовка ячейки
- - - Отрисовка всех ячеек
- - - Изменение случайной свободной ячейки
- - - Запуск игры
- - - Очистка доски
- Класс `Cell`, который содержит в себе информацию о ячейке
- Вынесены цвета ячеек в объект
- Панель с информацией о текущей игре

### Скриншоты/видяшка (если есть)
![image](https://github.com/Damir-prg/coffee-owls/assets/78173146/379dfb71-a793-42f4-a005-73cac4703c8a)

2024-05-07 07:01 UTC, olgadimova reviewed
Отличная работа, оставила несколько комментариев.

2024-05-07 18:29 UTC, Damir-prg commented on packages/client/src/widgets/GameCanvas/lib/board.ts
> +      Board.instance.pasteNewCell();
Добавил для того, чтобы на старте игры сразу было две ячейки со значениями

2024-05-07 18:39 UTC, Damir-prg commented on packages/client/src/widgets/GameCanvas/lib/board.ts
> +    if (Board.instance && Board.instance.ctx) {
Это условие здесь нужно чтобы не использовать оператор опциональной последовательности `?.`, если выносить её в отдельный метод, то typescript не подхватывает результат и выводит:

- `'Board.instance' is possibly 'null'.`
- `'Board.instance.ctx' is possibly 'null'.`

Если есть пример, то буду рад изучить

2024-05-07 19:54 UTC, Medjestik approved these changes

2024-05-07 19:56 UTC, Medjestik commented on packages/client/src/widgets/GameCanvas/lib/board.ts
> +  private pasteNewCell() {
Может немного упростить этот метод? Например:
`  private pasteNewCell() {
    const emptyCells = this.cells.flat().filter((cell) => !cell.value);

    if (!emptyCells.length) {
      console.log('Игра закончена, ходов больше нет :(');
      return;
    }

    const index = Math.floor(Math.random() * emptyCells.length);
    const newCell = emptyCells[index];

    newCell.value = 2 * Math.ceil(Math.random() * 2) as ICellProps['value'];
    this.drawCell(newCell);
  }`

2024-05-08 06:28 UTC, olgadimova approved these changes

2024-05-08 16:58 UTC, kate-lozovaya requested changes
Спасибо за комментарии к коду и подробное описание ПР )
Оставила несколько предложений/вопросов к ПР. Ответь на них и призывац меня к ревью

2024-05-08 16:58 UTC, kate-lozovaya commented on packages/client/src/widgets/GameCanvas/lib/board.ts
> +    if (Board.instance && Board.instance.ctx) {
[Вопрос]
А почему здесь не хочешь использовать оператор опциональной последовательности `?.`?

[Предложние]
Попробуй для возвращаемого значения метода поставить тип 
```
const checkIsBoard = (instance: Board | null): instance is Board => {//checks}
```

2024-05-08 16:58 UTC, kate-lozovaya commented on packages/client/src/shared/constants/game/types/ModeEnum.ts
> +export const gameModeTranslate = {
согласна, добавь тип

2024-05-08 16:58 UTC, kate-lozovaya commented on packages/client/src/widgets/GameCanvas/lib/board.ts
> +        const coordX = col * this.cellWidth + 5 * (col + 1);
[Предложение]
5 лучше вынести в константу, чтобы можно было настраивать это значение

2024-05-08 16:58 UTC, kate-lozovaya commented on packages/client/src/widgets/GameCanvas/lib/board.ts
> +    // this.ctx.rect(cell.coordX, cell.coordY, this.cellWidth, this.cellWidth);
[Вопрос]
Комментарий еще нужен?

2024-05-08 16:58 UTC, kate-lozovaya commented on packages/client/src/widgets/GameCanvas/lib/board.ts
> +  private drawCell(cell: Cell) {
[Исправление]
Отрисовка `Cell` больше относится к самому классу `Cell`, а не к `Board`. Предлагаю перенести метод в класс `Cell`

2024-05-08 16:58 UTC, kate-lozovaya commented on packages/client/src/widgets/GameCanvas/ui/GameBoard.tsx
> +      const height = ref.current.parentElement?.offsetHeight ?? 640;
[Предложение]
Тут будет надежнее ширину тоже проверить и выбирать минимальное значение. Устройство может быть вертикальным, тогда часть канваса не влезет в экран

2024-05-08 16:58 UTC, kate-lozovaya commented on packages/client/src/pages/Game/lib/GameScreens.tsx
> +    <GameContentContainer>
[Вопрос]
Не хочешь унести `GameContentContainer` внутрь компонентов `StartGameForm` и др?
Хочется тут видеть простое определение экран - компонент, чтобы сам StartGameForm определял, как будет выглядеть стартовый экран. Вряд ли `StartGameForm` и др будут еще где-то переиспользоваться

2024-05-10 11:09 UTC, Damir-prg commented on packages/client/src/pages/Game/lib/GameScreens.tsx
> +    <GameContentContainer>
Да, согласен. Перенесу в компоненты экранов игры

2024-05-10 11:54 UTC, Damir-prg commented on packages/client/src/widgets/GameCanvas/lib/board.ts
> +        const coordX = col * this.cellWidth + 5 * (col + 1);
Вынес в `private boardGap`

2024-05-10 11:55 UTC, Damir-prg commented on packages/client/src/widgets/GameCanvas/lib/board.ts
> +    // this.ctx.rect(cell.coordX, cell.coordY, this.cellWidth, this.cellWidth);
Забыл убрать, осталось когда рисовал ячейки, когда пробовал разные варианты отрисовки

2024-05-11 10:22 UTC, kate-lozovaya approved these changes
Оставила два комментария с предложениями. Исправления на твое усмотрение. 
Там ничего критичного, поэтому поставлю апрув

2024-05-11 10:22 UTC, kate-lozovaya commented on packages/client/src/widgets/GameCanvas/lib/board.ts
> +    return false;
[Предложение]
Можно сократить до `Boolean(instance)`

2024-05-11 10:22 UTC, kate-lozovaya commented on packages/client/src/widgets/GameCanvas/ui/GameBoard.tsx
> +      }
[Предложение]
Тут тоже можно немного сократить. Точнее убрать if. Посмотри, как тебе больше нравится
```ts
const DEFAULT_SIZE = 640; // константа, которую можно создать вне компонента, чтобы она не пересоздавалась на ререндеры
 const { offsetHeight = DEFAULT_SIZE, offsetWidth = DEFAULT_SIZE } = ref.current.parentElement;

const size = Math.min(offsetHeight, offsetWidth);
```

2024-05-11 13:01 UTC, merged