COF-73: Добавить OAuth авторизацию с Яндекс ID
Damir-prg/coffee-owls pull request #37
Opened 2024-06-09 18:29 UTC by olgadimova

### Какую задачу решаем

Добавлена кнопка "Войти c Яндекс ID" на начальную страницу логина и последующее перенаправление на страницу начала игры при успешном подтверждении авторизации. В качестве адреса перенаправления используется localhost:3000, который необходимо добавить в переменные окружения по типу env.example

### Скриншоты/видяшка (если есть)

<img width="1203" alt="Screenshot 2024-06-09 at 21 20 46" src="https://github.com/Damir-prg/coffee-owls/assets/38855943/6497939d-30a7-4294-adab-e14ed5ef2099">

### TBD (если есть)

2024-06-10 06:39 UTC, LemonGrace approved these changes
Отлично получилось!

2024-06-10 07:43 UTC, Medjestik approved these changes
Интересная задача, ты круто справилась!

2024-06-10 13:07 UTC, olgadimova commented on packages/client/src/widgets/WithRoutes/WithRoutes.tsx
Так сложно сказать как лучше, потому что надо по коду смотреть будет ли это все работать при условии получения данных с сервера(то есть после того как ты мр свой сделаешь). Вынесла его именно сюда потому что redirect url стоит localhost:3000, он на главную перебрасывает (по-моему другие роуты поставить нельзя например locahost:3000/sign-in), а ниже опустить он сразу на логин перебрасывать будет потому что в WithAuth проверяет залогинен ли пользователь.

2024-06-10 17:02 UTC, kate-lozovaya requested changes
Оставила несколько комментариев. 
Посмотри их, ответь и призывай меня к ревью

2024-06-10 17:53 UTC, Damir-prg approved these changes

2024-06-10 19:26 UTC, olgadimova commented on packages/client/src/widgets/WithRoutes/WithRoutes.tsx
> +  const isLoadingLogin = useRef<boolean>(false);
Пробовала сделать через useState, но думаю что в результате редиректов компонент ререндерится что приводит к тому что перезапрашиваются данные пользователя (user запрос) и не подхватываются куки авторизации даже при успешном логине (запрос yandex). При использовании useRef этого не происходит, один запрос на oauth/yandex, второй запрос подтягивает данные пользователя.

<img width="697" alt="Screenshot 2024-06-10 at 21 28 15" src="https://github.com/Damir-prg/coffee-owls/assets/38855943/6d605228-0a89-422b-8309-8ac5d089ec16">
<img width="681" alt="Screenshot 2024-06-10 at 21 14 48" src="https://github.com/Damir-prg/coffee-owls/assets/38855943/dcb502dc-6d71-45ee-b0f6-fb739fe9d8f5">

2024-06-10 19:28 UTC, olgadimova commented on packages/client/src/shared/api/oauthApi/oauthApi.ts
> +export const loginYandex = (data: TYandexLoginRequest): Promise<unknown> => {
Поправила тут тип

2024-06-11 07:40 UTC, kate-lozovaya approved these changes
👍🏻

2024-06-11 11:56 UTC, merged