COF-79: Переключение тем (клиентская часть)
Damir-prg/coffee-owls pull request #45
Opened 2024-06-22 13:08 UTC by eprikhodko

### Какую задачу решаем
Необходимо добавить функционал переключения тем приложения на клиенте.
https://linear.app/coffee-owls/issue/COF-79/pereklyuchenie-tem-klientskaya-chast

### Что было сделано
Добавил в приложение темную тему, добавил кнопку для переключения темы.

### Скриншоты/видяшка (если есть)
![2024-06-22_15-06](https://github.com/Damir-prg/coffee-owls/assets/74785156/f656d4e8-6098-47cb-9986-160c3165a2d5)

### TBD (если есть)

2024-06-22 13:18 UTC, Damir-prg approved these changes

2024-06-22 13:19 UTC, LemonGrace approved these changes

2024-06-22 13:31 UTC, olgadimova approved these changes
Хорошая работа!

2024-06-22 17:57 UTC, Medjestik approved these changes
Отличная работа

2024-06-23 01:03 UTC, kyzinatra commented on packages/client/src/shared/components/PageHeader/PageHeader.tsx
> +    dispatch(setTheme(newTheme));
Можно лучше: если добавится 3 тема, то придется переписывать этот код. Нарушается open-closed принцип
Стоит именно передавать выбранную тему, а не угадывать ихсодя из прошлой

2024-06-23 01:04 UTC, kyzinatra commented on packages/client/src/shared/components/PageHeader/PageHeader.tsx
> +        СМЕНИТЬ ТЕМУ
Можно лучше: стоит сделать список из тем. Можно добавить auto

2024-06-23 01:08 UTC, kyzinatra commented on packages/client/src/shared/store/themeSlice.ts
> +    },
Надо исправить: `localStorage` это внешний эффект, а в редьюсерах не должно быть никаких внешных эффектов. Есть специальные библиотеки, которые предоставляют middleware для синхронизации полей redux и storage. Стоит использовать их, или написать собственный middleware. Можно также сделать подобный код, более простой код:

```js

const theme = useSelector(getTheme)

useEffect(() => {
    // сюда можно добавить логику установки темы из localStorage в redux через dispatch, если theme === null
    localStorage.setItem('theme', theme);
},[theme])

```

Этот код можно вынести в компонент `ThemeProvider` или как-то так назвать, и он будет следить за темой и синхронизировать ее в `localStorage`

2024-06-23 01:09 UTC, kyzinatra requested changes
Отличная работа! В целом переключение тем реализовано хорошо. Сейчас есть только проблема с использованием эффекта в redux reducer. Так делать не стоит. Стоит поправить этот момент и ваша работа будет принята. В комментариях я рассписал несколько способов, чтобы это сделать

2024-06-24 16:43 UTC, eprikhodko commented on packages/client/src/shared/store/themeSlice.ts
> +    },
Спасибо за ревью! Внес правки, добавил компонент `ThemeProvider` и убрал внешние эффекты из редьюсеров.

2024-06-25 12:18 UTC, merged